### PR TITLE
allow manual override of Y-Axis MinValue and MaxValue

### LINKED ISSUE #43: Set y axis scale?
Is it possible to set the Y axis scale, rather than have it automatically set from the data?

### PR DESCRIPTION
**Pull request by markusressel**
This PR adds the ability to set a custom Y-Axis range on line graphs.

The graph in the top left has been set to `0.0 .. 11.0`

The graph in the top right has been set to `-1.5 .. 1.5`
The sin values have also been shifted "downwards" (back to the 0 origin actually) to visualize a graph that reaches negative values.

image

For the custom axis range constraints to work they have to be set manually each time `SetData()` is called, since `SetData()` calculates an automatic range internally, which overrides the custom range. This behavior is probably not ideal yet, feel free to suggest something better or implement something better yourself.

This PR also allows the usage of negative values within the data slice, I think this is something that previously also wasn't possible (but I am not entirely sure on that one).

fixes #43

### CODE REVIEW

**Comment by markusressel** [comment]
@navidys Note that this PR needs changes after #67 is merged, since it doesn't respect `math.NaN` values yet for calculating the max and min values of the data slice. I have already done those changes in my fork though, so I can quickly update the PR when it comes to that.

**Comment by navidys** [comment]
Hi @markusressel 

Thanks for the note, I won't merge this until the previous PR is merged and you have applied the changes to this one.

Thanks

**Comment by navidys** [comment]
Hi @markusressel 

I've merged the previous PR, you can apply you update regarding`math.NaN` and push again.

I think you need to rebase your branch also so due to previous PR merge.

Regards

**Comment by markusressel** [comment]
@navidys 
Should be all set now!

**Comment by navidys** [comment]
Hi @markusressel 

I am wondering why the line chart (dot mode) Y label is stating from 1.00 instead of 0.00 ?

image

**Review by navidys — COMMENTED** [review]
Hi @markusressel 

Can you create /demos/plot_\<name\>/ directory and put your example there instead of overwirting the current one. 

Also please create a README.md and screenshot of your example under that directory to follow the same structures as other examples

Regards

**Comment by markusressel** [comment]
@navidys
> I am wondering why the line chart (dot mode) Y label is stating from 1.00 instead of 0.00 ?

The axis are automatically scaled to the Max **and** Min values now. Since the smallest value in the dataset of the "line chart (dot mode)" is `1`, this is the value that is used for the first Y axis label.

Now that you ask about it, it might be a kind of breaking change, at least visually, since existing examples will look different. 
 I thought it would be an improvement, since f.ex. a genuine "sin(x)" graph would now alutomatically be displayed in the range `-1 .. 1`, but that was not the case before.

Should we create a configuration option to leave it to the user if they want to use automatic minimum scaling or is it okay to update the existing example images?

**Comment by navidys** [comment]
Hi @markusressel 
Yea I think it's better to create an option for auto scaling (e.g. 'YAxisAutoScale(val bool) ) with default false.

Thanks

**Comment by markusressel** [comment]
@navidys what about Y axis max value though? that was already autoscaled before. Simply adding a config option `YAxisAutoScale` set to `false` would also disable that... wouldn't it?

I think we need to separate Max and Min to keep compatibility, so:

`YAxisAutoScaleMin(val bool)` with default `false`
`YAxisAutoScaleMax(val bool)` with default `true`

**Comment by markusressel** [comment]
Old Plot with new config option defaults:
image

New Plot example with Custom Ranges:
image

**Comment by navidys** [comment]
True let's add two different functions for max and min values.
 Thanks for reminding me.

**Comment by navidys** [comment]
Just a note, in your commit you are using public variables for autoscal min and max, please make them private and create two functions in order to set those values.

**Comment by markusressel** [comment]
@navidys that wasn't intentional, fixed it.

Not sure how to fix the lint issues though, seems like a refactoring would be necessary.
Also not sure about the commit message thingy.

**Comment by navidys** [comment]
Thanks for that, I can fix the lint if I still have permission to your forked repo.

Will do it tomorrow morning since a bit late here 😉 and release a new version.

Thanks for your PRs.

**Comment by markusressel** [comment]
Thx, my pleasure!

However, there is still an issue with drawing out of bounds:

image

I am looking into it.

EDIT: solved.

**Comment by markusressel** [comment]
Hmm seems like method complexity gets really out of hand when trying to fix those out of bounds issues, and I am not sure using the `height` property is the way to go since it seems like this value includes the graph border and not just the graph area itself.

Also, even when doing so, graphs can still "bleed into each other" somehow, not sure whats going on there (notice the green in the top left):

image

Note that this "bleeding" is not a new issue. I have observed this in fan2go-tui already before I have started to work on these PRs.

**Comment by markusressel** [comment]
Hmm I have a theory:

Drawing braille lines gets wonky when at really small scales (zoomed in a lot).
A braille line requires two data points to draw a line between them, f.ex. Point A and Point B.
If say Point A is within, but Point B is beyond the available `Rect` space though we have a problem, since we should draw Point A but NOT draw Point B to the screen. We also cannot completely ignore Point B though since there might still be valid braille points to draw between point A and point B up until the point of reaching the bounds of the plot `Rect`.

This is an example of how it looks like now, you can see that the lines are "cut off" prematurely:
image

In more extreme instances, the line is skipped completely, because both Point A and Point B are out of bounds, but since the line between them would intersect the visible area there should still be a line drawn.

I am not sure how to handle this at this point. I think it would require a lot of changes in a couple of places to make this proper and its kind of an edge case, at least for the current use-cases of this library I guess. It works fine if the custom range set by the lib consumer includes the whole source dataset, which is the sole original case that existed (since the graph was always automatically scaled to match the data in Y direction).

I think I would like to propose to leave it at this even with this PR and maybe improve this down the line. Otherwise the amount of work needed to get this going fully may simply be too much.


**About drawing out of bounds:**
Thats still something I would like to fix though, since drawing over other graphs is really ugly. I guess this could be fixed using Z order of stuff, but it feels wrong. Since implementing the correct logic to handle the small scale (previous topic) is too complex right now, I would suggest to simply ignore values that are out of bounds and draw a point braille in that case. Its not ideal, but much simpler to implement.

EDIT: the out of bounds stuff should now be fixed, please have a look.

EDIT2: Another example image of the "demo", including holes within the data as well as the sin/cos graph moved into the negative range:
image

**Pull request merged**
