### PR TITLE
Expose GetPlotRect in public interface

### LINKED ISSUE #42: Any way to get the inner width/height of a chart?
This library is awesome and I'm finding it a joy to work with. Thank you!

I'm trying to create a line chart that gets updated in real time. So the rightmost value represents the latest data, with old data scrolling off the left of the chart. I'm having trouble aligning the latest data to the right edge though. Ideally I need to know exactly how many points can be displayed, so I can calculate how much data to hand to SetData. The width of chart Box is close, but it's not exact because of the axes.

I looked through the API and didn't find any obvious way to do this. The demo with updating charts simply shows more sin data when I make it larger, ie it doesn't have this alignment problem.

### PR DESCRIPTION
**Pull request by anderspitman**
Fixes #42

### CODE REVIEW

**Comment by navidys** [comment]
Hi @anderspitman 
It's perfect however there are two failures in checks
1. The git commits need to be signed
2. Golangci-lint: put a dot at the end of the comment of function description

**Comment by anderspitman** [comment]
I'll try and get this fixed tomorrow.

**Comment by anderspitman** [comment]
@navidys should be good to go

**Comment by navidys** [comment]
@anderspitman thanks

**Comment by navidys** [comment]
LGTM

**Pull request merged**
