### PR TITLE
Delete bar items

### PR DESCRIPTION
**Pull request by Topvennie**
Adds the ability to delete bar items

### CODE REVIEW

**Comment by navidys** [comment]
Hi @Topvennie 

Thanks for the PR, can u sign your commits and fix the golangci failure.

Regards

**Comment by navidys** [comment]
Hi @Topvennie 

Thanks for the PR, CI test is showing two failure. can you please:

1. Sign your commits
2. Fix golang-ci lint issue

Regards

**Comment by Topvennie** [comment]
@navidys 

I've fixed the linting issue and signed my commit by using `git commit -S -m "..."

**Comment by navidys** [comment]
Hi @Topvennie 

Still the DCO check is failing, did u sign all three commits ? 

Maybe u can squash all the commits and only have one signed commit.

Regards

**Pull request merged**
